version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Run tests
          command: yarn test
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    docker:
      - image: "cimg/base:stable"
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - node/install:
          node-version: "16.13"
      - run:
          name: Build code bundle
          command: yarn build
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package to npm
          command: npm publish
      - add_ssh_keys:
          fingerprints:
            - "$GH_DEPLOY_KEY"
      - run:
          name: Deploy docs to gh pages
          command: |
            yarn add gh-pages
            git config user.email "shriyanjithen@gmail.com"
            git config user.name "jithenshriyan"
            gh-pages --dotfiles --message "[skip ci] Updates" --dist ~/repo/docs

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
